name: Download cache and Upload

on:
  workflow_dispatch:
    inputs:
      cache_key:
        description: 'Cache key'
        required: true
        type: string
      version:
        description: 'Cache hash version'
        required: true
        type: string

jobs:
  cache-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # - name: Restore cache
      #   uses: actions/cache/restore@v3
      #   with:
      #     # Path won't be actually used, we will match by 'version'.
      #     path: .
      #     key: ${{ github.event.inputs.cache_key }}

      # - name: Upload cached folder as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: cache-artifact
      #     path: |
      #       /home/runner/work/**/*.tzst

