name: test-makefile-logs

on:
  workflow_dispatch:

jobs:
  test-makefile-logs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

    - name: Run cmake
      run: |
        env
        cmake --version
        pip install rich
        export FORCE_COLOR="1"
        python -c "from rich import print; print('[green]Hello, world[/green]')"
        python -c "print('\033[33mHello, world!\033[0m')"
        cd test-makefile-logs
        mkdir build
        cd build
        cmake ..
        make -j
