name: test-makefile-logs

on:
  workflow_dispatch:

jobs:
  test-makefile-logs:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
      CLICOLOR_FORCE: "1"
      CMAKE_COLOR_DIAGNOSTICS: "ON"

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

    - uses: astral-sh/setup-uv@v7

    - name: Run cmake
      run: |
        env
        uv tool install cmake
        cmake --version
        pip install rich
        python -c "from rich import print; print('[green]Hello, world[/green]')"
        python -c "print('\033[33mHello, world!\033[0m')"
        cd test-makefile-logs
        mkdir build
        cd build
        cmake ..
        grep -r COLOR . --color=always
        make -j VERBOSE=1
